# Release.toml

# 不自动发布（仅修改版本号）
publish = false

# 不推送到远程仓库
push = false

# 创建 Git tag
tag = true

# 不签名提交和 tag
sign-commit = false
sign-tag = false

# 跳过验证（比如 workspace 检查）
allow-branch = ["main"]

# 使用工作目录而不是 Git tracked files
package = true

# 使用 cargo-release 的标准 changelog 功能
[changelog]
path = "CHANGELOG.md"
# 启用自动生成 changelog
auto = true